### ISSUE TITLE
cabal build plutus-starter-pab results in compilation error 

### ISSUE THREAD

**Issue by whosystem** [input-output-hk/plutus-starter#9]
<----- machine version 
 lsb_release -a 
-- | --
No LSB modules are available. |  
Distributor ID: | Ubuntu
Description: | Ubuntu 20.04.2 LTS
Release: | 20.04
Codename: | focal

------------------------------------->

Completed    plutus-core-0.1.0.0 (lib)

Failed to build eventful-sql-common-0.2.0.
Build log (
/home/cardano/.cabal/logs/ghc-8.10.4/eventful-sql-common-0.2.0-148c8b23e1b4f4438c2e6514b3764f8be7781341566db89b002d2e94748d8533.log
):
Configuring library for eventful-sql-common-0.2.0..
Preprocessing library for eventful-sql-common-0.2.0..
Building library for eventful-sql-common-0.2.0..
[1 of 5] Compiling Eventful.Store.Sql.JSONString ( src/Eventful/Store/Sql/JSONString.hs, dist/build/Eventful/Store/Sql/JSONString.o, dist/build/Eventful/Store/Sql/JSONString.dyn_o )
[2 of 5] Compiling Eventful.Store.Sql.Orphans ( src/Eventful/Store/Sql/Orphans.hs, dist/build/Eventful/Store/Sql/Orphans.o, dist/build/Eventful/Store/Sql/Orphans.dyn_o )

src/Eventful/Store/Sql/Orphans.hs:19:21: warning: [-Wdeprecations]
    In the use of data constructor ‘PersistDbSpecific’
    (imported from Database.Persist.Sql, but defined in persistent-2.11.0.2:Database.Persist.Types.Base):
    Deprecated: "Deprecated since 2.11 because of inconsistent escaping behavior across backends. The Postgres backend escapes these values, while the MySQL backend does not. If you are using this, please switch to 'PersistLiteral' or 'PersistLiteralEscaped' based on your needs."
   |
19 |   fromPersistValue (PersistDbSpecific t) =
   |                     ^^^^^^^^^^^^^^^^^
[3 of 5] Compiling Eventful.Store.Sql.Operations ( src/Eventful/Store/Sql/Operations.hs, dist/build/Eventful/Store/Sql/Operations.o, dist/build/Eventful/Store/Sql/Operations.dyn_o )

src/Eventful/Store/Sql/Operations.hs:18:1: warning: [-Wunused-imports]
    The import of ‘maybe’ from module ‘Data.Maybe’ is redundant
   |
18 | import Data.Maybe (listToMaybe, maybe)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Eventful/Store/Sql/Operations.hs:19:1: warning: [-Wunused-imports]
    The import of ‘Data.Monoid’ is redundant
      except perhaps to import instances from ‘Data.Monoid’
    To import instances alone, use: import Data.Monoid()
   |
19 | import Data.Monoid ((<>))
   | ^^^^^^^^^^^^^^^^^^^^^^^^^
[4 of 5] Compiling Eventful.Store.Sql.DefaultEntity ( src/Eventful/Store/Sql/DefaultEntity.hs, dist/build/Eventful/Store/Sql/DefaultEntity.o, dist/build/Eventful/Store/Sql/DefaultEntity.dyn_o )

src/Eventful/Store/Sql/DefaultEntity.hs:25:1: error:
    Generating Persistent entities now requires the MultiParamTypeClasses language extension. Please enable it by copy/pasting this line to the top of your file:

{-# LANGUAGE MultiParamTypeClasses #-}
   |
25 | share [mkPersist sqlSettings, mkMigrate "migrateSqlEvent"] [persistLowerCase|
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
cabal: Failed to build eventful-sql-common-0.2.0 (which is required by
exe:plutus-starter-pab from plutus-starter-0.1.0.0). See the build log above
for details.

**Comment by michaelpj** [comment]
Please open issues in the main plutus repo.
